### PR TITLE
this will forever be named dwon (jordan's epic edits)

### PR DESCRIPTION
**Pull request by realKeiZerCodes**

### CODE REVIEW

**Comment by jaajko** [comment]
bam

**Review by jaajko — CHANGES_REQUESTED** [review]
it's a jpg o_O

**Comment by jaajko** [comment]
@realKeiZerCodes it works ow

**Comment by jaajko** [comment]
now

**Review by jaajko — APPROVED** [review]

**Review by jaajko — CHANGES_REQUESTED** [review]
hotlink protection affects pages.dev preview url

**Comment by realKeiZerCodes** [comment]
i did it are you proud of me thanks

**Comment by jaajko** [comment]
yay

**Comment by jaajko** [comment]
i'll upload the image to a hotlink-ok folder

**Comment by realKeiZerCodes** [comment]
> hotlink protection affects pages.dev preview url

does that mean the page will work when deployed officially but not during preview?

**Comment by realKeiZerCodes** [comment]
> i'll upload the image to a hotlink-ok folder

aight

**Comment by jaajko** [comment]
yes

**Comment by realKeiZerCodes** [comment]
bing bong

**Comment by jaajko** [comment]
@realKeiZerCodes test it

**Comment by realKeiZerCodes** [comment]
it works pog

**Comment by realKeiZerCodes** [comment]
have you set a size for the videoplayer or did you leave it default? cos it's kind of small compared to the window size

**Comment by jaajko** [comment]
> 
it's small so it looks good on both mobile and desktop platforms

**Comment by realKeiZerCodes** [comment]
> > 
> 
> it's small so it looks good on both mobile and desktop platforms

ohhhh ok

**Comment by jaajko** [comment]
in the future, i could create a mobile-only version, but you can fullscreen the videos anyways so :P

**Review by jaajko — APPROVED** [review]

**Comment by realKeiZerCodes** [comment]
true true

**Comment by jaajko** [comment]
o nooo

**Comment by jaajko** [comment]
commit to the pr to avoid conflicts

**Comment by realKeiZerCodes** [comment]
oops i just saw it
how do i resolve a conflict then? might as well learn

**Comment by jaajko** [comment]
good question kek

**Comment by realKeiZerCodes** [comment]
LOL i'll just reverse the changes i made then

**Comment by jaajko** [comment]
already did

**Comment by realKeiZerCodes** [comment]
aight cool

**Comment by jaajko** [comment]
make the changes you want, i'll check this pr every minute or so, i'll write the page for josu!ps

**Comment by realKeiZerCodes** [comment]
i did a poopookaka and accidentally created a new branch

**Comment by realKeiZerCodes** [comment]
i fixed it! >:D

**Comment by jaajko** [comment]
> i did a poopookaka and accidentally created a new branch

lmaooo

**Comment by realKeiZerCodes** [comment]
that's about all the changes I'd like, it was already pretty good. changed the avatar size to be 50% bigger and changed the text above the video player to be white

**Comment by jaajko** [comment]
give me a sec to check something before i merge

**Comment by jaajko** [comment]
merged :)

**Pull request merged**
